"""add auth_events table

Revision ID: 6cd7079d4a5c
Revises: cb70710b1d22
Create Date: 2026-07-16 13:04:58.144635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sentry.storage.models


# revision identifiers, used by Alembic.
revision: str = '6cd7079d4a5c'
down_revision: Union[str, Sequence[str], None] = 'cb70710b1d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_events_account', 'auth_events', ['account'], unique=False)
    op.create_index('ix_auth_events_occurred_at', 'auth_events', ['occurred_at'], unique=False)
    op.create_index('ux_auth_events_event_key', 'auth_events', ['event_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_auth_events_event_key', table_name='auth_events')
    op.drop_index('ix_auth_events_occurred_at', table_name='auth_events')
    op.drop_index('ix_auth_events_account', table_name='auth_events')
    op.drop_table('auth_events')
    # ### end Alembic commands ###
