"""baseline schema

Revision ID: cb70710b1d22
Revises: 
Create Date: 2026-07-16 09:51:39.995265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sentry.storage.models


# revision identifiers, used by Alembic.
revision: str = 'cb70710b1d22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('created_at', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_dedup_key', 'alerts', ['dedup_key'], unique=False)
    op.create_index('ix_alerts_rule_id_created_at', 'alerts', ['rule_id', 'created_at'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('file_integrity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('perms_octal', sa.String(length=8), nullable=True),
    sa.Column('mtime', sentry.storage.models.UTCDateTime(), nullable=True),
    sa.Column('first_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_integrity_identity_key', 'file_integrity', ['identity_key'], unique=False)
    op.create_index('ix_file_integrity_open_last_seen', 'file_integrity', ['last_seen'], unique=False, sqlite_where=sa.text('still_present = 1'))
    op.create_index('ix_file_integrity_path', 'file_integrity', ['path'], unique=False)
    op.create_index('ux_file_integrity_open_identity', 'file_integrity', ['identity_key'], unique=True, sqlite_where=sa.text('still_present = 1'))
    op.create_table('network_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('laddr', sa.String(length=64), nullable=False),
    sa.Column('lport', sa.Integer(), nullable=False),
    sa.Column('raddr', sa.String(length=64), nullable=False),
    sa.Column('rport', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('exe_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_network_observations_identity_key', 'network_observations', ['identity_key'], unique=False)
    op.create_index('ix_network_observations_open_last_seen', 'network_observations', ['last_seen'], unique=False, sqlite_where=sa.text('still_present = 1'))
    op.create_index('ux_network_observations_open_identity', 'network_observations', ['identity_key'], unique=True, sqlite_where=sa.text('still_present = 1'))
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('package_manager', sa.String(length=16), nullable=False),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_packages_identity_key', 'packages', ['identity_key'], unique=False)
    op.create_index('ix_packages_name', 'packages', ['name'], unique=False)
    op.create_index('ix_packages_open_last_seen', 'packages', ['last_seen'], unique=False, sqlite_where=sa.text('still_present = 1'))
    op.create_index('ux_packages_open_identity', 'packages', ['identity_key'], unique=True, sqlite_where=sa.text('still_present = 1'))
    op.create_table('persistence_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanism', sa.String(length=32), nullable=False),
    sa.Column('unit_or_path', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('owner_user', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('first_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persistence_entries_identity_key', 'persistence_entries', ['identity_key'], unique=False)
    op.create_index('ix_persistence_entries_open_last_seen', 'persistence_entries', ['last_seen'], unique=False, sqlite_where=sa.text('still_present = 1'))
    op.create_index('ux_persistence_entries_open_identity', 'persistence_entries', ['identity_key'], unique=True, sqlite_where=sa.text('still_present = 1'))
    op.create_table('process_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('ppid', sa.Integer(), nullable=False),
    sa.Column('exe_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('cmdline', sa.Text(), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.Float(), nullable=False),
    sa.Column('first_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_process_observations_identity_key', 'process_observations', ['identity_key'], unique=False)
    op.create_index('ix_process_observations_open_last_seen', 'process_observations', ['last_seen'], unique=False, sqlite_where=sa.text('still_present = 1'))
    op.create_index('ux_process_observations_open_identity', 'process_observations', ['identity_key'], unique=True, sqlite_where=sa.text('still_present = 1'))
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('match_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('expires_at', sentry.storage.models.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suppressions_rule_id_scope', 'suppressions', ['rule_id', 'scope'], unique=False)
    op.create_table('system_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('kernel_version', sa.String(length=255), nullable=False),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('cpu_count', sa.Integer(), nullable=False),
    sa.Column('cpu_model', sa.Text(), nullable=True),
    sa.Column('mem_total_bytes', sa.Integer(), nullable=False),
    sa.Column('disks_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_inventory_collected_at', 'system_inventory', ['collected_at'], unique=False)
    op.create_table('users_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('home_dir', sa.Text(), nullable=True),
    sa.Column('shell', sa.Text(), nullable=True),
    sa.Column('groups_json', sa.Text(), nullable=False),
    sa.Column('is_sudoer', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sentry.storage.models.UTCDateTime(), nullable=False),
    sa.Column('still_present', sa.Boolean(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_groups_identity_key', 'users_groups', ['identity_key'], unique=False)
    op.create_index('ix_users_groups_open_last_seen', 'users_groups', ['last_seen'], unique=False, sqlite_where=sa.text('still_present = 1'))
    op.create_index('ux_users_groups_open_identity', 'users_groups', ['identity_key'], unique=True, sqlite_where=sa.text('still_present = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_users_groups_open_identity', table_name='users_groups', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_users_groups_open_last_seen', table_name='users_groups', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_users_groups_identity_key', table_name='users_groups')
    op.drop_table('users_groups')
    op.drop_index('ix_system_inventory_collected_at', table_name='system_inventory')
    op.drop_table('system_inventory')
    op.drop_index('ix_suppressions_rule_id_scope', table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index('ux_process_observations_open_identity', table_name='process_observations', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_process_observations_open_last_seen', table_name='process_observations', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_process_observations_identity_key', table_name='process_observations')
    op.drop_table('process_observations')
    op.drop_index('ux_persistence_entries_open_identity', table_name='persistence_entries', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_persistence_entries_open_last_seen', table_name='persistence_entries', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_persistence_entries_identity_key', table_name='persistence_entries')
    op.drop_table('persistence_entries')
    op.drop_index('ux_packages_open_identity', table_name='packages', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_packages_open_last_seen', table_name='packages', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_packages_name', table_name='packages')
    op.drop_index('ix_packages_identity_key', table_name='packages')
    op.drop_table('packages')
    op.drop_index('ux_network_observations_open_identity', table_name='network_observations', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_network_observations_open_last_seen', table_name='network_observations', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_network_observations_identity_key', table_name='network_observations')
    op.drop_table('network_observations')
    op.drop_index('ux_file_integrity_open_identity', table_name='file_integrity', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_file_integrity_path', table_name='file_integrity')
    op.drop_index('ix_file_integrity_open_last_seen', table_name='file_integrity', sqlite_where=sa.text('still_present = 1'))
    op.drop_index('ix_file_integrity_identity_key', table_name='file_integrity')
    op.drop_table('file_integrity')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_rule_id_created_at', table_name='alerts')
    op.drop_index('ix_alerts_dedup_key', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
